// File Automatically generated by the ROOT Script Compiler 

#ifdef __CINT__

#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;

#pragma link C++ defined_in /afs/cern.ch/user/k/kjaffel/CMSSW_10_2_18/src/TTbarCalib/TTbarEventAnalysis.h;
#pragma link C++ defined_in "/afs/cern.ch/user/k/kjaffel/CMSSW_10_2_18/src/TTbarCalib/TTbarEventAnalysis.cc";

#endif
